dubbo:
  application:
    name: web-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 20880
  annotation:
    package: 'cn.edu.ahau.web'
  consumer: # 消费者服务版本
    timeout: 500000
    check: false
    version: 1.0.0 #dubbo默认版本号，在url显示为default.version=xxx
swagger:
  enable: true
